//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaTrader.Custom.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NinjaTrader.Custom.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09.03.2020 22:00    1.1349&apos;9  1.1494&apos;3  1.1335&apos;9  1.1437&apos;3  841265
        ///10.03.2020 22:00    1.1429&apos;0  1.1458&apos;0  1.1274&apos;8  1.1279&apos;9  791647
        ///11.03.2020 22:00    1.1276&apos;4  1.1366&apos;7  1.1257&apos;5  1.1269&apos;3  554804
        ///12.03.2020 22:00    1.1269&apos;5  1.1333&apos;6  1.1055&apos;5  1.1184&apos;5  857108
        ///13.03.2020 22:00    1.1184&apos;4  1.1221&apos;1  1.1054&apos;9  1.1103&apos;7  795392
        ///16.03.2020 22:00    1.1073&apos;9  1.1236&apos;5  1.1072&apos;9  1.1180&apos;1  1149541
        ///17.03.2020 22:00    1.1180&apos;9  1.1189&apos;1  1.0955&apos;0  1.0996&apos;2  859210
        ///18.03.2020 22:00    1.0996&apos;4  1.104 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eurusd_day001_from_07_03_2020_till_18_04_2021 {
            get {
                return ResourceManager.GetString("eurusd_day001_from_07_03_2020_till_18_04_2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.09.2022 23:01    0.9590&apos;9  0.9591&apos;9  0.9590&apos;9  0.9591&apos;9  9
        ///27.09.2022 23:02    0.9591&apos;9  0.9591&apos;9  0.9587&apos;5  0.9587&apos;7  5
        ///27.09.2022 23:04    0.9587&apos;7  0.9587&apos;7  0.9587&apos;7  0.9587&apos;7  2
        ///27.09.2022 23:05    0.9587&apos;9  0.9589&apos;0  0.9587&apos;9  0.9589&apos;0  8
        ///27.09.2022 23:06    0.9589&apos;2  0.9589&apos;4  0.9589&apos;2  0.9589&apos;4  10
        ///27.09.2022 23:07    0.9589&apos;5  0.9591&apos;5  0.9589&apos;4  0.9589&apos;4  85
        ///27.09.2022 23:09    0.9589&apos;4  0.9589&apos;4  0.9589&apos;4  0.9589&apos;4  3
        ///27.09.2022 23:10    0.9589&apos;1  0.9589&apos;1  0.9589&apos;1  0.9589&apos;1  1
        ///27.09. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eurusd_minute001_from_28_09_2022_till_29_09_2022 {
            get {
                return ResourceManager.GetString("eurusd_minute001_from_28_09_2022_till_29_09_2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.09.2022 23:03    0.9590&apos;9  0.9591&apos;9  0.9587&apos;5  0.9587&apos;7  14
        ///27.09.2022 23:06    0.9587&apos;7  0.9589&apos;4  0.9587&apos;7  0.9589&apos;4  20
        ///27.09.2022 23:09    0.9589&apos;5  0.9591&apos;5  0.9589&apos;4  0.9589&apos;4  88
        ///27.09.2022 23:12    0.9589&apos;1  0.9589&apos;1  0.9589&apos;0  0.9589&apos;1  22
        ///27.09.2022 23:15    0.9589&apos;1  0.9591&apos;2  0.9589&apos;0  0.9589&apos;1  33
        ///27.09.2022 23:18    0.9589&apos;1  0.9590&apos;0  0.9589&apos;1  0.9589&apos;4  33
        ///27.09.2022 23:21    0.9589&apos;3  0.9589&apos;4  0.9589&apos;1  0.9589&apos;1  12
        ///27.09.2022 23:27    0.9589&apos;1  0.9595&apos;2  0.9588&apos;8  0.9594&apos;1  374        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eurusd_minute003_from_28_09_2022_till_29_09_2022 {
            get {
                return ResourceManager.GetString("eurusd_minute003_from_28_09_2022_till_29_09_2022", resourceCulture);
            }
        }
    }
}
